services:
  builds:
    build:
      context: .
      dockerfile: web.dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - LISTEN_PORT=${PORT}
      - HOST_PORT=${PORT}
      - KEY=${KEY}
    volumes:
      - ./backend:/app/backend
